wget http://upload.wikimedia.org/wikipedia/commons/3/3e/WikEd_error.png
wget http://upload.wikimedia.org/wikipedia/commons/3/34/WikEd_find_ahead.png
wget http://upload.wikimedia.org/wikipedia/commons/7/75/WikEd_find_all.png
wget http://upload.wikimedia.org/wikipedia/commons/a/ad/WikEd_find_next.png
wget http://upload.wikimedia.org/wikipedia/commons/f/f5/WikEd_find_prev.png
wget http://upload.wikimedia.org/wikipedia/commons/8/86/WikEd_fix_all.png
wget http://upload.wikimedia.org/wikipedia/commons/3/30/WikEd_fix_basic.png
wget http://upload.wikimedia.org/wikipedia/commons/0/00/WikEd_fix_caps.png
wget http://upload.wikimedia.org/wikipedia/commons/d/d4/WikEd_fix_unicode.png
wget http://upload.wikimedia.org/wikipedia/commons/e/e7/WikEd_fix_chem.png
wget http://upload.wikimedia.org/wikipedia/commons/e/e5/WikEd_fix_dash.png
wget http://upload.wikimedia.org/wikipedia/commons/0/05/WikEd_fix_html.png
wget http://upload.wikimedia.org/wikipedia/commons/3/3f/WikEd_fix_math.png
wget http://upload.wikimedia.org/wikipedia/commons/d/db/WikEd_fix_punct.png
wget http://upload.wikimedia.org/wikipedia/commons/9/94/WikEd_fix_reg-ex-typo.png
wget http://upload.wikimedia.org/wikipedia/commons/6/69/WikEd_fix_units.png
wget http://upload.wikimedia.org/wikipedia/commons/7/71/WikEd_font_size.png
wget http://upload.wikimedia.org/wikipedia/commons/d/d3/WikEd_fullscreen.png
wget http://upload.wikimedia.org/wikipedia/commons/9/96/WikEd_get_selection.png
wget http://upload.wikimedia.org/wikipedia/commons/a/ad/WikEd_grip.png
wget http://upload.wikimedia.org/wikipedia/commons/0/07/WikEd_heading.png
wget http://upload.wikimedia.org/wikipedia/commons/6/67/WikEd_syntax.png
wget http://upload.wikimedia.org/wikipedia/commons/3/37/WikEd_image.png
wget http://upload.wikimedia.org/wikipedia/commons/7/7a/WikEd_indent_list.png
wget http://upload.wikimedia.org/wikipedia/commons/d/d4/WikEd_italic.png
wget http://upload.wikimedia.org/wikipedia/commons/5/54/WikEd_jump_next.png
wget http://upload.wikimedia.org/wikipedia/commons/6/67/WikEd_logo.png
wget http://upload.wikimedia.org/wikipedia/commons/5/5a/WikEd_nowiki.png
wget http://upload.wikimedia.org/wikipedia/commons/3/3b/WikEd_number_list.png
wget http://upload.wikimedia.org/wikipedia/commons/c/c7/WikEd_jump_prev.png
wget http://upload.wikimedia.org/wikipedia/commons/3/31/WikEd_preview.png
wget http://upload.wikimedia.org/wikipedia/commons/f/fa/WikEd_redirect.png
wget http://upload.wikimedia.org/wikipedia/commons/d/d7/WikEd_redo.png
wget http://upload.wikimedia.org/wikipedia/commons/b/ba/WikEd_ref.png
wget http://upload.wikimedia.org/wikipedia/commons/0/0b/WikEd_ref_hide.png
wget http://upload.wikimedia.org/wikipedia/commons/6/66/WikEd_references.png
wget http://upload.wikimedia.org/wikipedia/commons/2/2d/WikEd_redo_all.png
wget http://upload.wikimedia.org/wikipedia/commons/6/6a/WikEd_regexp.png
wget http://upload.wikimedia.org/wikipedia/commons/2/2a/WikEd_replace_all.png
wget http://upload.wikimedia.org/wikipedia/commons/b/b0/WikEd_replace_next.png
wget http://upload.wikimedia.org/wikipedia/commons/a/a1/WikEd_replace_prev.png
wget http://upload.wikimedia.org/wikipedia/commons/1/13/WikEd_align_top.png
wget http://upload.wikimedia.org/wikipedia/commons/3/37/WikEd_align_preview.png
wget http://upload.wikimedia.org/wikipedia/commons/a/a8/WikEd_align_down.png
wget http://upload.wikimedia.org/wikipedia/commons/5/58/WikEd_align_preview_down.png
wget http://upload.wikimedia.org/wikipedia/commons/0/02/WikEd_source.png
wget http://upload.wikimedia.org/wikipedia/commons/0/06/WikEd_strikethrough.png
wget http://upload.wikimedia.org/wikipedia/commons/9/9e/WikEd_subscript.png
wget http://upload.wikimedia.org/wikipedia/commons/b/bf/WikEd_superscript.png
wget http://upload.wikimedia.org/wikipedia/commons/e/e7/WikEd_tab.png
wget http://upload.wikimedia.org/wikipedia/commons/b/bd/WikEd_table.png
wget http://upload.wikimedia.org/wikipedia/commons/c/cd/WikEd_textify.png
wget http://upload.wikimedia.org/wikipedia/commons/2/21/WikEd_underline.png
wget http://upload.wikimedia.org/wikipedia/commons/e/e6/WikEd_undo.png
wget http://upload.wikimedia.org/wikipedia/commons/0/08/WikEd_undo_all.png
wget http://upload.wikimedia.org/wikipedia/commons/8/8a/WikEd_unknown.png
wget http://upload.wikimedia.org/wikipedia/commons/6/67/WikEd_logo.png
wget http://upload.wikimedia.org/wikipedia/commons/e/e0/WikEd_using.png
wget http://upload.wikimedia.org/wikipedia/commons/1/16/WikEd_weblink.png
wget http://upload.wikimedia.org/wikipedia/commons/c/c6/WikEdDiff.png
wget http://upload.wikimedia.org/wikipedia/commons/9/9f/WikEd_wikify.png
wget http://upload.wikimedia.org/wikipedia/commons/2/21/WikEd_wikilink.png
wget http://upload.wikimedia.org/wikipedia/commons/0/00/WikEd_table_edit.png
wget http://upload.wikimedia.org/wikipedia/commons/8/8a/WikEd_unknown.png
wget http://upload.wikimedia.org/wikipedia/commons/7/7c/WikEd_sort.png
